import logging
from app.extensions import db
from app.models.document import Document
from app.models.agreement_temp import (
    TempAgmtHeader, 
    TempAgmtModels, 
    TempAgmtMdlNormal, 
    TempAgmtCommitment
)

logger = logging.getLogger(__name__)

def save_extracted_tables_to_db(document_id: int, extracted_json: dict):
    """
    Parses the JSON tables generated by the LLM and maps them to SQLAlchemy staging models.
    """
    doc = Document.query.get(document_id)
    if not doc:
        raise ValueError(f"Document ID {document_id} not found in database.")

    doc.confidence_score = int(extracted_json.get("confidence_score", 0))

    tables = extracted_json.get("tables", [])
    
    # WHY: We need to store references to the parent tables as we create them. 
    # Because we are using auto-incrementing integer IDs now, we have to wait for the database 
    # to generate the ID for the Header before we can attach the Models and Commitments to it.
    current_header = None
    model_mapping = {}  # Maps the string MODEL_SEQ from the AI to the actual database model.id

    for table in tables:
        title = table.get("title", "").upper()
        headers = table.get("headers", [])
        rows = table.get("rows", [])

        for row in rows:
            row_data = dict(zip(headers, row))
            row_data = sanitize_row_data(row_data)
            
            # 1. Map Agreement Header
            if "HEADER" in title or "AGMT_STATUS" in headers:
                current_header = TempAgmtHeader()
                current_header.document_id = document_id # WHY: Explicitly link to the Document ID
                _populate_record(current_header, row_data)
                
                db.session.add(current_header)
                # WHY: flush() pushes the object to the database immediately without finalizing the transaction.
                # This generates `current_header.id` so we can use it for the child tables below.
                db.session.flush() 

            # 2. Map Agreement Models
            elif "MODELS" in title or "MODEL_TYPE" in headers:
                if not current_header: continue # Safety check
                
                model = TempAgmtModels()
                model.header_id = current_header.id # WHY: Relational link via the new integer key
                _populate_record(model, row_data)
                
                db.session.add(model)
                db.session.flush() # WHY: Generate model.id immediately
                
                # WHY: Save this model's ID so the Rate rows know which parent to attach to
                seq = row_data.get("MODEL_SEQ")
                if seq is not None:
                    model_mapping[str(seq)] = model.id

            # 3. Map Rate Details
            elif "RATE" in title or "CHARGE_FIELD" in headers:
                rate = TempAgmtMdlNormal()
                
                # WHY: Find the parent model's real database ID using the sequence number the AI gave us
                ai_seq = str(row_data.get("MODEL_SEQ", "1"))
                rate.model_id = model_mapping.get(ai_seq) 
                
                _populate_record(rate, row_data)
                
                if hasattr(rate, 'CHARGE_FIELD') and rate.CHARGE_FIELD:
                    try:
                        rate.CHARGE_FIELD = float(rate.CHARGE_FIELD)
                    except ValueError:
                        rate.CHARGE_FIELD = 0.0
                        
                db.session.add(rate)

            # 4. Map Commitments
            elif "COMMITMENT" in title or "COMMITMENT_TYPE" in headers:
                if not current_header: continue
                
                commitment = TempAgmtCommitment()
                commitment.header_id = current_header.id # WHY: Link to header surrogate key
                _populate_record(commitment, row_data)
                
                if hasattr(commitment, 'AMOUNT') and commitment.AMOUNT:
                    try:
                        commitment.AMOUNT = float(commitment.AMOUNT)
                    except ValueError:
                        commitment.AMOUNT = 0.0
                        
                db.session.add(commitment)
    

    db.session.commit()
    logger.info(f"Successfully saved all extracted tables for document {document_id} to DB.")


def _populate_record(sqlalchemy_record, row_data: dict):
    for key, value in row_data.items():
        if hasattr(sqlalchemy_record, key):
            clean_value = None if value == "" else value
            setattr(sqlalchemy_record, key, clean_value)


def sanitize_row_data(row_dict: dict) -> dict:
    for key, value in row_dict.items():
        if isinstance(value, str):
            val_upper = value.strip().upper()
            if val_upper in ('Y', 'YES', 'TRUE'):
                row_dict[key] = True
            elif val_upper in ('N', 'NO', 'FALSE'):
                row_dict[key] = False
    return row_dict