"""Initial schema rebuild

Revision ID: b6cb821a5854
Revises: 
Create Date: 2026-07-24 07:24:20.318415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cb821a5854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGMT_HEADER_STG',
    sa.Column('AGMT_ID', sa.String(length=50), nullable=False),
    sa.Column('SENDER', sa.String(length=100), nullable=True),
    sa.Column('RP', sa.String(length=100), nullable=True),
    sa.Column('TAP_DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('REV_NO', sa.Integer(), nullable=True),
    sa.Column('START_DATE', sa.Date(), nullable=True),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('REMARKS', sa.Text(), nullable=True),
    sa.Column('DATA_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('INVOICE_AMT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('USER_ACT_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('CURRENCY_CODE', sa.String(length=3), nullable=True),
    sa.Column('AUTO_RENEWAL', sa.Boolean(), nullable=True),
    sa.Column('IS_GROUP_RP', sa.Boolean(), nullable=True),
    sa.Column('AGMT_STATUS', sa.String(length=20), nullable=True),
    sa.Column('TOTAL_AGMT_MONTH', sa.Integer(), nullable=True),
    sa.Column('IS_RERATING_REQD', sa.Boolean(), nullable=True),
    sa.Column('GPRS_RULE', sa.String(length=50), nullable=True),
    sa.Column('GPRS_LIMIT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('BASELINE_RULE', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('COMMIT_RULE', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('IS_GROUP_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('PARENT_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('REGEN_REQUIRED', sa.Boolean(), nullable=True),
    sa.Column('IS_TAP_LEVEL_AGMT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_RP', sa.Boolean(), nullable=True),
    sa.Column('BASELINE_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('MASTER_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_USER', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('AGMT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('BULK_ID', sa.String(length=50), nullable=True),
    sa.Column('IS_BASELINE_APPLICABLE', sa.Boolean(), nullable=True),
    sa.Column('AGMT_LEVEL_RC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('SPL_REMARKS', sa.Text(), nullable=True),
    sa.Column('CURRENCY_AGMT', sa.String(length=3), nullable=True),
    sa.Column('IMSI_ACTIVATION_TYPE', sa.String(length=20), nullable=True),
    sa.Column('IMSI_ACTIVATION_CRITERIA', sa.String(length=100), nullable=True),
    sa.Column('RAP_CHRG', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('RAP_VOL', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('EXCHANGE_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_LEVEL_RC_VAR_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_DOC_STATUS', sa.String(length=20), nullable=True),
    sa.Column('AGMT_NEGO_STATUS', sa.String(length=20), nullable=True),
    sa.Column('INC_IN_ACCRL_RPT', sa.Boolean(), nullable=True),
    sa.Column('IS_M2M_APPLCBL', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED_BY', sa.String(length=50), nullable=True),
    sa.Column('AGMT_VERIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('HAS_UNRESOLVED_CONFLICT', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('AGMT_ID')
    )
    op.create_table('mnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('AGMT_COMMITMENT',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('COMMITMENT_NAME', sa.String(length=100), nullable=True),
    sa.Column('COMMITMENT_TYPE', sa.String(length=50), nullable=True),
    sa.Column('DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('AMOUNT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('CAPTURE_RATE_PCT', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('PARTY_FROM', sa.String(length=100), nullable=True),
    sa.Column('PARTY_TO', sa.String(length=100), nullable=True),
    sa.Column('SOURCE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('CONFLICT_FLAG', sa.Boolean(), nullable=True),
    sa.Column('CONFLICT_NOTE', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['AGMT_ID'], ['AGMT_HEADER_STG.AGMT_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AGMT_MODELS_STG',
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=False),
    sa.Column('MODEL_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('MODEL_NAME', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['AGMT_ID'], ['AGMT_HEADER_STG.AGMT_ID'], ),
    sa.PrimaryKeyConstraint('MODEL_SEQ')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('baseline_data', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AGMT_MDL_NORMAL_STG',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('REC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('ZONE_CODE', sa.String(length=20), nullable=True),
    sa.Column('RATE_CURRENCY', sa.String(length=3), nullable=True),
    sa.Column('PRA_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('DISC_RATE_PERC', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('CHARGE_INCLUDE_TAX', sa.Boolean(), nullable=True),
    sa.Column('CHARGE_FIELD', sa.Numeric(precision=50), nullable=True),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AGMT_ID'], ['AGMT_HEADER_STG.AGMT_ID'], ),
    sa.ForeignKeyConstraint(['MODEL_SEQ'], ['AGMT_MODELS_STG.MODEL_SEQ'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_records')
    op.drop_table('audit_logs')
    op.drop_table('AGMT_MDL_NORMAL_STG')
    op.drop_table('documents')
    op.drop_table('AGMT_MODELS_STG')
    op.drop_table('AGMT_COMMITMENT')
    op.drop_table('users')
    op.drop_table('mnos')
    op.drop_table('AGMT_HEADER_STG')
    # ### end Alembic commands ###
