"""add_current_step

Revision ID: ff68365cfd01
Revises: 37d0b2412f40
Create Date: 2026-08-06 07:46:31.936964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff68365cfd01'
down_revision = '37d0b2412f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_agmt_header',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mno_id', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('SENDER', sa.String(length=100), nullable=True),
    sa.Column('RP', sa.String(length=255), nullable=True),
    sa.Column('TAP_DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('REV_NO', sa.Integer(), nullable=True),
    sa.Column('START_DATE', sa.Date(), nullable=True),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('REMARKS', sa.Text(), nullable=True),
    sa.Column('DATA_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('INVOICE_AMT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('USER_ACT_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('CURRENCY_CODE', sa.String(length=3), nullable=True),
    sa.Column('AUTO_RENEWAL', sa.Boolean(), nullable=True),
    sa.Column('IS_GROUP_RP', sa.Boolean(), nullable=True),
    sa.Column('AGMT_STATUS', sa.String(length=20), nullable=True),
    sa.Column('TOTAL_AGMT_MONTH', sa.Integer(), nullable=True),
    sa.Column('IS_RERATING_REQD', sa.Boolean(), nullable=True),
    sa.Column('GPRS_RULE', sa.String(length=50), nullable=True),
    sa.Column('GPRS_LIMIT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('BASELINE_RULE', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('COMMIT_RULE', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('IS_GROUP_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('PARENT_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('REGEN_REQUIRED', sa.Boolean(), nullable=True),
    sa.Column('IS_TAP_LEVEL_AGMT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_RP', sa.Boolean(), nullable=True),
    sa.Column('BASELINE_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('MASTER_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_USER', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('AGMT_TYPE', sa.String(length=255), nullable=True),
    sa.Column('BULK_ID', sa.String(length=50), nullable=True),
    sa.Column('IS_BASELINE_APPLICABLE', sa.Boolean(), nullable=True),
    sa.Column('AGMT_LEVEL_RC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('SPL_REMARKS', sa.Text(), nullable=True),
    sa.Column('CURRENCY_AGMT', sa.String(length=3), nullable=True),
    sa.Column('IMSI_ACTIVATION_TYPE', sa.String(length=20), nullable=True),
    sa.Column('IMSI_ACTIVATION_CRITERIA', sa.String(length=100), nullable=True),
    sa.Column('RAP_CHRG', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('RAP_VOL', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('EXCHANGE_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_LEVEL_RC_VAR_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_DOC_STATUS', sa.String(length=20), nullable=True),
    sa.Column('AGMT_NEGO_STATUS', sa.String(length=20), nullable=True),
    sa.Column('INC_IN_ACCRL_RPT', sa.Boolean(), nullable=True),
    sa.Column('IS_M2M_APPLCBL', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED_BY', sa.String(length=50), nullable=True),
    sa.Column('AGMT_VERIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('HAS_UNRESOLVED_CONFLICT', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mno_id'], ['mnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='archive'
    )
    op.create_table('prod_agmt_header',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mno_id', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('SENDER', sa.String(length=100), nullable=True),
    sa.Column('RP', sa.String(length=255), nullable=True),
    sa.Column('TAP_DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('REV_NO', sa.Integer(), nullable=True),
    sa.Column('START_DATE', sa.Date(), nullable=True),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('REMARKS', sa.Text(), nullable=True),
    sa.Column('DATA_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('INVOICE_AMT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('USER_ACT_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('CURRENCY_CODE', sa.String(length=3), nullable=True),
    sa.Column('AUTO_RENEWAL', sa.Boolean(), nullable=True),
    sa.Column('IS_GROUP_RP', sa.Boolean(), nullable=True),
    sa.Column('AGMT_STATUS', sa.String(length=20), nullable=True),
    sa.Column('TOTAL_AGMT_MONTH', sa.Integer(), nullable=True),
    sa.Column('IS_RERATING_REQD', sa.Boolean(), nullable=True),
    sa.Column('GPRS_RULE', sa.String(length=50), nullable=True),
    sa.Column('GPRS_LIMIT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('BASELINE_RULE', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('COMMIT_RULE', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('IS_GROUP_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('PARENT_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('REGEN_REQUIRED', sa.Boolean(), nullable=True),
    sa.Column('IS_TAP_LEVEL_AGMT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_RP', sa.Boolean(), nullable=True),
    sa.Column('BASELINE_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('MASTER_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_USER', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('AGMT_TYPE', sa.String(length=255), nullable=True),
    sa.Column('BULK_ID', sa.String(length=50), nullable=True),
    sa.Column('IS_BASELINE_APPLICABLE', sa.Boolean(), nullable=True),
    sa.Column('AGMT_LEVEL_RC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('SPL_REMARKS', sa.Text(), nullable=True),
    sa.Column('CURRENCY_AGMT', sa.String(length=3), nullable=True),
    sa.Column('IMSI_ACTIVATION_TYPE', sa.String(length=20), nullable=True),
    sa.Column('IMSI_ACTIVATION_CRITERIA', sa.String(length=100), nullable=True),
    sa.Column('RAP_CHRG', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('RAP_VOL', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('EXCHANGE_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_LEVEL_RC_VAR_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_DOC_STATUS', sa.String(length=20), nullable=True),
    sa.Column('AGMT_NEGO_STATUS', sa.String(length=20), nullable=True),
    sa.Column('INC_IN_ACCRL_RPT', sa.Boolean(), nullable=True),
    sa.Column('IS_M2M_APPLCBL', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED_BY', sa.String(length=50), nullable=True),
    sa.Column('AGMT_VERIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('HAS_UNRESOLVED_CONFLICT', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mno_id'], ['mnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('RP', name='uq_prod_active_rp'),
    schema='prod'
    )
    op.create_table('archive_agmt_commitment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('COMMITMENT_NAME', sa.String(length=100), nullable=True),
    sa.Column('COMMITMENT_TYPE', sa.String(length=50), nullable=True),
    sa.Column('DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('AMOUNT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('CAPTURE_RATE_PCT', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('PARTY_FROM', sa.String(length=100), nullable=True),
    sa.Column('PARTY_TO', sa.String(length=100), nullable=True),
    sa.Column('SOURCE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('CONFLICT_FLAG', sa.Boolean(), nullable=True),
    sa.Column('CONFLICT_NOTE', sa.Text(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['archive.archive_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='archive'
    )
    op.create_table('archive_agmt_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=False),
    sa.Column('MODEL_TYPE', sa.String(length=20), nullable=True),
    sa.Column('MODEL_NAME', sa.String(length=100), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['archive.archive_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='archive'
    )
    op.create_table('prod_agmt_commitment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('COMMITMENT_NAME', sa.String(length=100), nullable=True),
    sa.Column('COMMITMENT_TYPE', sa.String(length=50), nullable=True),
    sa.Column('DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('AMOUNT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('CAPTURE_RATE_PCT', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('PARTY_FROM', sa.String(length=100), nullable=True),
    sa.Column('PARTY_TO', sa.String(length=100), nullable=True),
    sa.Column('SOURCE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('CONFLICT_FLAG', sa.Boolean(), nullable=True),
    sa.Column('CONFLICT_NOTE', sa.Text(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['prod.prod_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prod'
    )
    op.create_table('prod_agmt_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=False),
    sa.Column('MODEL_TYPE', sa.String(length=20), nullable=True),
    sa.Column('MODEL_NAME', sa.String(length=100), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['prod.prod_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prod'
    )
    op.create_table('temp_agmt_header',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('SENDER', sa.String(length=100), nullable=True),
    sa.Column('RP', sa.String(length=255), nullable=True),
    sa.Column('TAP_DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('REV_NO', sa.Integer(), nullable=True),
    sa.Column('START_DATE', sa.Date(), nullable=True),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('REMARKS', sa.Text(), nullable=True),
    sa.Column('DATA_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('INVOICE_AMT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('USER_ACT_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('CURRENCY_CODE', sa.String(length=3), nullable=True),
    sa.Column('AUTO_RENEWAL', sa.Boolean(), nullable=True),
    sa.Column('IS_GROUP_RP', sa.Boolean(), nullable=True),
    sa.Column('AGMT_STATUS', sa.String(length=20), nullable=True),
    sa.Column('TOTAL_AGMT_MONTH', sa.Integer(), nullable=True),
    sa.Column('IS_RERATING_REQD', sa.Boolean(), nullable=True),
    sa.Column('GPRS_RULE', sa.String(length=50), nullable=True),
    sa.Column('GPRS_LIMIT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('BASELINE_RULE', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('BASELINE_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('COMMIT_RULE', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_BASE_FIELD', sa.String(length=50), nullable=True),
    sa.Column('COMMIT_VALUE', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('IS_GROUP_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('PARENT_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('REGEN_REQUIRED', sa.Boolean(), nullable=True),
    sa.Column('IS_TAP_LEVEL_AGMT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_CLIENT', sa.Boolean(), nullable=True),
    sa.Column('IS_PARTIAL_RP', sa.Boolean(), nullable=True),
    sa.Column('BASELINE_LEVEL', sa.String(length=20), nullable=True),
    sa.Column('MASTER_AGMT_ID', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_USER', sa.String(length=50), nullable=True),
    sa.Column('MODIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('AGMT_TYPE', sa.String(length=255), nullable=True),
    sa.Column('BULK_ID', sa.String(length=50), nullable=True),
    sa.Column('IS_BASELINE_APPLICABLE', sa.Boolean(), nullable=True),
    sa.Column('AGMT_LEVEL_RC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('SPL_REMARKS', sa.Text(), nullable=True),
    sa.Column('CURRENCY_AGMT', sa.String(length=3), nullable=True),
    sa.Column('IMSI_ACTIVATION_TYPE', sa.String(length=20), nullable=True),
    sa.Column('IMSI_ACTIVATION_CRITERIA', sa.String(length=100), nullable=True),
    sa.Column('RAP_CHRG', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('RAP_VOL', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('EXCHANGE_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_LEVEL_RC_VAR_TYPE', sa.String(length=20), nullable=True),
    sa.Column('AGMT_DOC_STATUS', sa.String(length=20), nullable=True),
    sa.Column('AGMT_NEGO_STATUS', sa.String(length=20), nullable=True),
    sa.Column('INC_IN_ACCRL_RPT', sa.Boolean(), nullable=True),
    sa.Column('IS_M2M_APPLCBL', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED', sa.Boolean(), nullable=True),
    sa.Column('AGMT_VERIFIED_BY', sa.String(length=50), nullable=True),
    sa.Column('AGMT_VERIFIED_DATE', sa.DateTime(), nullable=True),
    sa.Column('HAS_UNRESOLVED_CONFLICT', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='temp'
    )
    op.create_table('archive_agmt_mdl_normal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('REC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('ZONE_CODE', sa.String(length=20), nullable=True),
    sa.Column('RATE_CURRENCY', sa.String(length=3), nullable=True),
    sa.Column('PRA_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('DISC_RATE_PERC', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('CHARGE_INCLUDE_TAX', sa.Boolean(), nullable=True),
    sa.Column('CHARGE_FIELD', sa.Numeric(precision=50), nullable=True),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['archive.archive_agmt_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='archive'
    )
    op.create_table('prod_agmt_mdl_normal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('REC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('ZONE_CODE', sa.String(length=20), nullable=True),
    sa.Column('RATE_CURRENCY', sa.String(length=3), nullable=True),
    sa.Column('PRA_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('DISC_RATE_PERC', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('CHARGE_INCLUDE_TAX', sa.Boolean(), nullable=True),
    sa.Column('CHARGE_FIELD', sa.Numeric(precision=50), nullable=True),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['prod.prod_agmt_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prod'
    )
    op.create_table('temp_agmt_commitment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('COMMITMENT_NAME', sa.String(length=100), nullable=True),
    sa.Column('COMMITMENT_TYPE', sa.String(length=50), nullable=True),
    sa.Column('DIRECTION', sa.String(length=20), nullable=True),
    sa.Column('AMOUNT', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('CAPTURE_RATE_PCT', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('PARTY_FROM', sa.String(length=100), nullable=True),
    sa.Column('PARTY_TO', sa.String(length=100), nullable=True),
    sa.Column('SOURCE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('CONFLICT_FLAG', sa.Boolean(), nullable=True),
    sa.Column('CONFLICT_NOTE', sa.Text(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['temp.temp_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='temp'
    )
    op.create_table('temp_agmt_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=False),
    sa.Column('MODEL_TYPE', sa.String(length=20), nullable=True),
    sa.Column('MODEL_NAME', sa.String(length=100), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['temp.temp_agmt_header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='temp'
    )
    op.create_table('temp_agmt_mdl_normal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('REC_TYPE', sa.String(length=20), nullable=True),
    sa.Column('ZONE_CODE', sa.String(length=20), nullable=True),
    sa.Column('RATE_CURRENCY', sa.String(length=3), nullable=True),
    sa.Column('PRA_RATE_TYPE', sa.String(length=20), nullable=True),
    sa.Column('DISC_RATE_PERC', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('CHARGE_INCLUDE_TAX', sa.Boolean(), nullable=True),
    sa.Column('CHARGE_FIELD', sa.Numeric(precision=50), nullable=True),
    sa.Column('MODEL_SEQ', sa.Integer(), nullable=True),
    sa.Column('AGMT_ID', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['temp.temp_agmt_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='temp'
    )
    with op.batch_alter_table('AGMT_HEADER_STG', schema=None) as batch_op:
        batch_op.drop_column('EXTRACTION_CONFIDENCE')

    with op.batch_alter_table('AGMT_MDL_NORMAL_STG', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('AGMT_MDL_NORMAL_STG_MODEL_SEQ_fkey'), type_='foreignkey')

    with op.batch_alter_table('AGMT_MODELS_STG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('uq_agmt_model_seq', ['AGMT_ID', 'MODEL_SEQ'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agmt_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('agmt_id')
        batch_op.drop_column('error_message')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('current_step')

    with op.batch_alter_table('AGMT_MODELS_STG', schema=None) as batch_op:
        batch_op.drop_constraint('uq_agmt_model_seq', type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('AGMT_MDL_NORMAL_STG', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('AGMT_MDL_NORMAL_STG_MODEL_SEQ_fkey'), 'AGMT_MODELS_STG', ['MODEL_SEQ'], ['MODEL_SEQ'])

    with op.batch_alter_table('AGMT_HEADER_STG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EXTRACTION_CONFIDENCE', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))

    op.drop_table('temp_agmt_mdl_normal', schema='temp')
    op.drop_table('temp_agmt_models', schema='temp')
    op.drop_table('temp_agmt_commitment', schema='temp')
    op.drop_table('prod_agmt_mdl_normal', schema='prod')
    op.drop_table('archive_agmt_mdl_normal', schema='archive')
    op.drop_table('temp_agmt_header', schema='temp')
    op.drop_table('prod_agmt_models', schema='prod')
    op.drop_table('prod_agmt_commitment', schema='prod')
    op.drop_table('archive_agmt_models', schema='archive')
    op.drop_table('archive_agmt_commitment', schema='archive')
    op.drop_table('prod_agmt_header', schema='prod')
    op.drop_table('archive_agmt_header', schema='archive')
    # ### end Alembic commands ###
